import type { GlitchChoice } from "./WorkbookActivity";

const CHOICES: Record<string, GlitchChoice[]> = {
  "case-01:pizza": [{ label: "The four slices are different sizes, so they are not equal fourths", correct: true }, { label: "Four slices always make fourths, even when their sizes differ", correct: false }, { label: "The largest slice should count as two fourths", correct: false }, { label: "The slices only need to have the same shape, not the same size", correct: false }],
  "case-01:chocolate": [{ label: "The three pieces are different sizes, so they are not equal thirds", correct: true }, { label: "Three cut lines mean the bar has been split into thirds", correct: false }, { label: "Each piece is a third because there are three pieces", correct: false }, { label: "The middle piece can be smaller and still be one third", correct: false }],
  "case-01:canvas": [{ label: "The dividing line is not in the middle, so the halves are unequal", correct: true }, { label: "Any one line across a shape makes two equal halves", correct: false }, { label: "The painted side is one half because only one side is painted", correct: false }, { label: "Two sections are always halves, even if one is wider", correct: false }],
  "case-02:bar": [{ label: "The bottom number counts only the blank blocks instead of all equal blocks", correct: true }, { label: "The top number should count every block, shaded and blank", correct: false }, { label: "The fraction should be 2/3 because two blocks are blank", correct: false }, { label: "The bottom number should match the number of shaded blocks", correct: false }],
  "case-02:crate": [{ label: "The top and bottom numbers are swapped", correct: true }, { label: "The fraction is right because both 1 and 4 appear in the picture", correct: false }, { label: "The top number should count every slot in the crate", correct: false }, { label: "The bottom number should count only the filled slot", correct: false }],
  "case-02:panels": [{ label: "The top number counts the dark panels instead of the selected panels", correct: true }, { label: "The top number should be 6 because there are six panels altogether", correct: false }, { label: "The bottom number should count only the light panels", correct: false }, { label: "The fraction is correct because two panels are dark", correct: false }],
  "case-03:tanks": [{ label: "The symbol says one tank has more, but the fractions show equal amounts", correct: true }, { label: "The tank with more sections must contain more fuel", correct: false }, { label: "The fraction with the larger bottom number is always larger", correct: false }, { label: "The amounts differ because the tanks use different-sized sections", correct: false }],
  "case-03:garden": [{ label: "The symbol says the areas differ, but both fractions cover the same area", correct: true }, { label: "The bed with more rows must have the larger fraction", correct: false }, { label: "The larger bottom number makes that garden bed larger", correct: false }, { label: "Equivalent fractions cannot use different numbers", correct: false }],
  "case-03:disks": [{ label: "The symbol says the data amounts differ, but both disks show the same amount", correct: true }, { label: "The disk with more slices must store more data", correct: false }, { label: "The fraction with more shaded pieces is always larger", correct: false }, { label: "The amounts cannot be equal because the denominators differ", correct: false }],
  "case-04:cargo": [{ label: "The comparison symbol points to the smaller fraction", correct: true }, { label: "With the same top number, the fraction with more pieces is larger", correct: false }, { label: "Both fractions are equal because both top numbers are 1", correct: false }, { label: "Eighths are larger than fourths because 8 is larger than 4", correct: false }],
  "case-04:coolant": [{ label: "The comparison symbol says 2/3 is smaller, even though thirds are larger pieces", correct: true }, { label: "Both fractions are equal because both top numbers are 2", correct: false }, { label: "2/5 is larger because 5 is larger than 3", correct: false }, { label: "More pieces on the bottom always means more coolant", correct: false }],
  "case-04:beams": [{ label: "The comparison symbol says 3/4 is shorter, even though fourths are larger pieces", correct: true }, { label: "Both fractions are equal because both top numbers are 3", correct: false }, { label: "3/8 is longer because 8 is larger than 4", correct: false }, { label: "A larger bottom number always makes a longer beam", correct: false }],
  "case-05:conveyor": [{ label: "The result’s bottom numbers were added instead of keeping the fifths", correct: true }, { label: "The top numbers should stay the same when adding fifths", correct: false }, { label: "The answer should use tenths because two fractions were combined", correct: false }, { label: "Both top and bottom numbers must always be added", correct: false }],
  "case-05:coolant": [{ label: "The result’s bottom numbers were subtracted instead of keeping the eighths", correct: true }, { label: "The bottom number should become 6 because two eighths were drained", correct: false }, { label: "Both top and bottom numbers must always be subtracted", correct: false }, { label: "The answer should be 3/6 because the tank has less coolant", correct: false }],
  "case-05:assembly": [{ label: "The result’s bottom numbers were added instead of keeping the sixths", correct: true }, { label: "The answer should use twelfths because two groups were joined", correct: false }, { label: "Both top and bottom numbers must be added when combining fractions", correct: false }, { label: "The bottom number should change whenever the top number changes", correct: false }],
  "case-06:blueprint": [{ label: "Different-sized fraction pieces were added before making equal-sized pieces", correct: true }, { label: "Only the top numbers need to match before fractions can be added", correct: false }, { label: "The bottom numbers can stay different if the top numbers are added", correct: false }, { label: "Fourth-size and half-size pieces can be counted together as they are", correct: false }],
  "case-06:paint": [{ label: "Paint measured with different grids was added before making matching pieces", correct: true }, { label: "Fractions can be added directly whenever both pictures show paint", correct: false }, { label: "Only the shaded pieces matter, so the grid sizes can be ignored", correct: false }, { label: "The denominators do not need to match when the numerators are added", correct: false }],
  "case-06:circuit": [{ label: "Different-sized fraction pieces were subtracted before making equal-sized pieces", correct: true }, { label: "Fractions can be subtracted directly whenever the top number is larger", correct: false }, { label: "Only the top numbers need to be subtracted; piece sizes do not matter", correct: false }, { label: "Eighth-size and fourth-size pieces can be removed from each other directly", correct: false }],
};

export function getGlitchChoices(caseNumber: string, subCase: string) {
  return CHOICES[`${caseNumber}:${subCase}`] ?? [];
}