/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrintablesRouteImport } from './routes/printables'
import { Route as PlayRouteImport } from './routes/play'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayIndexRouteImport } from './routes/play.index'
import { Route as PrintablesFractionsL1RouteImport } from './routes/printables.fractions-l1'
import { Route as PlayCase03RouteImport } from './routes/play.case-03'
import { Route as PlayCase02RouteImport } from './routes/play.case-02'
import { Route as PlayCase01RouteImport } from './routes/play.case-01'
import { Route as ApiChatCase03TanksRouteImport } from './routes/api/chat/case-03-tanks'
import { Route as ApiChatCase03GardenRouteImport } from './routes/api/chat/case-03-garden'
import { Route as ApiChatCase03DisksRouteImport } from './routes/api/chat/case-03-disks'
import { Route as ApiChatCase02PanelsRouteImport } from './routes/api/chat/case-02-panels'
import { Route as ApiChatCase02CrateRouteImport } from './routes/api/chat/case-02-crate'
import { Route as ApiChatCase02BarRouteImport } from './routes/api/chat/case-02-bar'
import { Route as ApiChatCase01ChocolateRouteImport } from './routes/api/chat/case-01-chocolate'
import { Route as ApiChatCase01CanvasRouteImport } from './routes/api/chat/case-01-canvas'
import { Route as ApiChatCase01RouteImport } from './routes/api/chat/case-01'

const PrintablesRoute = PrintablesRouteImport.update({
  id: '/printables',
  path: '/printables',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayIndexRoute = PlayIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlayRoute,
} as any)
const PrintablesFractionsL1Route = PrintablesFractionsL1RouteImport.update({
  id: '/fractions-l1',
  path: '/fractions-l1',
  getParentRoute: () => PrintablesRoute,
} as any)
const PlayCase03Route = PlayCase03RouteImport.update({
  id: '/case-03',
  path: '/case-03',
  getParentRoute: () => PlayRoute,
} as any)
const PlayCase02Route = PlayCase02RouteImport.update({
  id: '/case-02',
  path: '/case-02',
  getParentRoute: () => PlayRoute,
} as any)
const PlayCase01Route = PlayCase01RouteImport.update({
  id: '/case-01',
  path: '/case-01',
  getParentRoute: () => PlayRoute,
} as any)
const ApiChatCase03TanksRoute = ApiChatCase03TanksRouteImport.update({
  id: '/api/chat/case-03-tanks',
  path: '/api/chat/case-03-tanks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatCase03GardenRoute = ApiChatCase03GardenRouteImport.update({
  id: '/api/chat/case-03-garden',
  path: '/api/chat/case-03-garden',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatCase03DisksRoute = ApiChatCase03DisksRouteImport.update({
  id: '/api/chat/case-03-disks',
  path: '/api/chat/case-03-disks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatCase02PanelsRoute = ApiChatCase02PanelsRouteImport.update({
  id: '/api/chat/case-02-panels',
  path: '/api/chat/case-02-panels',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatCase02CrateRoute = ApiChatCase02CrateRouteImport.update({
  id: '/api/chat/case-02-crate',
  path: '/api/chat/case-02-crate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatCase02BarRoute = ApiChatCase02BarRouteImport.update({
  id: '/api/chat/case-02-bar',
  path: '/api/chat/case-02-bar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatCase01ChocolateRoute = ApiChatCase01ChocolateRouteImport.update({
  id: '/api/chat/case-01-chocolate',
  path: '/api/chat/case-01-chocolate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatCase01CanvasRoute = ApiChatCase01CanvasRouteImport.update({
  id: '/api/chat/case-01-canvas',
  path: '/api/chat/case-01-canvas',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatCase01Route = ApiChatCase01RouteImport.update({
  id: '/api/chat/case-01',
  path: '/api/chat/case-01',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/play': typeof PlayRouteWithChildren
  '/printables': typeof PrintablesRouteWithChildren
  '/play/case-01': typeof PlayCase01Route
  '/play/case-02': typeof PlayCase02Route
  '/play/case-03': typeof PlayCase03Route
  '/printables/fractions-l1': typeof PrintablesFractionsL1Route
  '/play/': typeof PlayIndexRoute
  '/api/chat/case-01': typeof ApiChatCase01Route
  '/api/chat/case-01-canvas': typeof ApiChatCase01CanvasRoute
  '/api/chat/case-01-chocolate': typeof ApiChatCase01ChocolateRoute
  '/api/chat/case-02-bar': typeof ApiChatCase02BarRoute
  '/api/chat/case-02-crate': typeof ApiChatCase02CrateRoute
  '/api/chat/case-02-panels': typeof ApiChatCase02PanelsRoute
  '/api/chat/case-03-disks': typeof ApiChatCase03DisksRoute
  '/api/chat/case-03-garden': typeof ApiChatCase03GardenRoute
  '/api/chat/case-03-tanks': typeof ApiChatCase03TanksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/printables': typeof PrintablesRouteWithChildren
  '/play/case-01': typeof PlayCase01Route
  '/play/case-02': typeof PlayCase02Route
  '/play/case-03': typeof PlayCase03Route
  '/printables/fractions-l1': typeof PrintablesFractionsL1Route
  '/play': typeof PlayIndexRoute
  '/api/chat/case-01': typeof ApiChatCase01Route
  '/api/chat/case-01-canvas': typeof ApiChatCase01CanvasRoute
  '/api/chat/case-01-chocolate': typeof ApiChatCase01ChocolateRoute
  '/api/chat/case-02-bar': typeof ApiChatCase02BarRoute
  '/api/chat/case-02-crate': typeof ApiChatCase02CrateRoute
  '/api/chat/case-02-panels': typeof ApiChatCase02PanelsRoute
  '/api/chat/case-03-disks': typeof ApiChatCase03DisksRoute
  '/api/chat/case-03-garden': typeof ApiChatCase03GardenRoute
  '/api/chat/case-03-tanks': typeof ApiChatCase03TanksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/play': typeof PlayRouteWithChildren
  '/printables': typeof PrintablesRouteWithChildren
  '/play/case-01': typeof PlayCase01Route
  '/play/case-02': typeof PlayCase02Route
  '/play/case-03': typeof PlayCase03Route
  '/printables/fractions-l1': typeof PrintablesFractionsL1Route
  '/play/': typeof PlayIndexRoute
  '/api/chat/case-01': typeof ApiChatCase01Route
  '/api/chat/case-01-canvas': typeof ApiChatCase01CanvasRoute
  '/api/chat/case-01-chocolate': typeof ApiChatCase01ChocolateRoute
  '/api/chat/case-02-bar': typeof ApiChatCase02BarRoute
  '/api/chat/case-02-crate': typeof ApiChatCase02CrateRoute
  '/api/chat/case-02-panels': typeof ApiChatCase02PanelsRoute
  '/api/chat/case-03-disks': typeof ApiChatCase03DisksRoute
  '/api/chat/case-03-garden': typeof ApiChatCase03GardenRoute
  '/api/chat/case-03-tanks': typeof ApiChatCase03TanksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/play'
    | '/printables'
    | '/play/case-01'
    | '/play/case-02'
    | '/play/case-03'
    | '/printables/fractions-l1'
    | '/play/'
    | '/api/chat/case-01'
    | '/api/chat/case-01-canvas'
    | '/api/chat/case-01-chocolate'
    | '/api/chat/case-02-bar'
    | '/api/chat/case-02-crate'
    | '/api/chat/case-02-panels'
    | '/api/chat/case-03-disks'
    | '/api/chat/case-03-garden'
    | '/api/chat/case-03-tanks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/printables'
    | '/play/case-01'
    | '/play/case-02'
    | '/play/case-03'
    | '/printables/fractions-l1'
    | '/play'
    | '/api/chat/case-01'
    | '/api/chat/case-01-canvas'
    | '/api/chat/case-01-chocolate'
    | '/api/chat/case-02-bar'
    | '/api/chat/case-02-crate'
    | '/api/chat/case-02-panels'
    | '/api/chat/case-03-disks'
    | '/api/chat/case-03-garden'
    | '/api/chat/case-03-tanks'
  id:
    | '__root__'
    | '/'
    | '/play'
    | '/printables'
    | '/play/case-01'
    | '/play/case-02'
    | '/play/case-03'
    | '/printables/fractions-l1'
    | '/play/'
    | '/api/chat/case-01'
    | '/api/chat/case-01-canvas'
    | '/api/chat/case-01-chocolate'
    | '/api/chat/case-02-bar'
    | '/api/chat/case-02-crate'
    | '/api/chat/case-02-panels'
    | '/api/chat/case-03-disks'
    | '/api/chat/case-03-garden'
    | '/api/chat/case-03-tanks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlayRoute: typeof PlayRouteWithChildren
  PrintablesRoute: typeof PrintablesRouteWithChildren
  ApiChatCase01Route: typeof ApiChatCase01Route
  ApiChatCase01CanvasRoute: typeof ApiChatCase01CanvasRoute
  ApiChatCase01ChocolateRoute: typeof ApiChatCase01ChocolateRoute
  ApiChatCase02BarRoute: typeof ApiChatCase02BarRoute
  ApiChatCase02CrateRoute: typeof ApiChatCase02CrateRoute
  ApiChatCase02PanelsRoute: typeof ApiChatCase02PanelsRoute
  ApiChatCase03DisksRoute: typeof ApiChatCase03DisksRoute
  ApiChatCase03GardenRoute: typeof ApiChatCase03GardenRoute
  ApiChatCase03TanksRoute: typeof ApiChatCase03TanksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/printables': {
      id: '/printables'
      path: '/printables'
      fullPath: '/printables'
      preLoaderRoute: typeof PrintablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/': {
      id: '/play/'
      path: '/'
      fullPath: '/play/'
      preLoaderRoute: typeof PlayIndexRouteImport
      parentRoute: typeof PlayRoute
    }
    '/printables/fractions-l1': {
      id: '/printables/fractions-l1'
      path: '/fractions-l1'
      fullPath: '/printables/fractions-l1'
      preLoaderRoute: typeof PrintablesFractionsL1RouteImport
      parentRoute: typeof PrintablesRoute
    }
    '/play/case-03': {
      id: '/play/case-03'
      path: '/case-03'
      fullPath: '/play/case-03'
      preLoaderRoute: typeof PlayCase03RouteImport
      parentRoute: typeof PlayRoute
    }
    '/play/case-02': {
      id: '/play/case-02'
      path: '/case-02'
      fullPath: '/play/case-02'
      preLoaderRoute: typeof PlayCase02RouteImport
      parentRoute: typeof PlayRoute
    }
    '/play/case-01': {
      id: '/play/case-01'
      path: '/case-01'
      fullPath: '/play/case-01'
      preLoaderRoute: typeof PlayCase01RouteImport
      parentRoute: typeof PlayRoute
    }
    '/api/chat/case-03-tanks': {
      id: '/api/chat/case-03-tanks'
      path: '/api/chat/case-03-tanks'
      fullPath: '/api/chat/case-03-tanks'
      preLoaderRoute: typeof ApiChatCase03TanksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat/case-03-garden': {
      id: '/api/chat/case-03-garden'
      path: '/api/chat/case-03-garden'
      fullPath: '/api/chat/case-03-garden'
      preLoaderRoute: typeof ApiChatCase03GardenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat/case-03-disks': {
      id: '/api/chat/case-03-disks'
      path: '/api/chat/case-03-disks'
      fullPath: '/api/chat/case-03-disks'
      preLoaderRoute: typeof ApiChatCase03DisksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat/case-02-panels': {
      id: '/api/chat/case-02-panels'
      path: '/api/chat/case-02-panels'
      fullPath: '/api/chat/case-02-panels'
      preLoaderRoute: typeof ApiChatCase02PanelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat/case-02-crate': {
      id: '/api/chat/case-02-crate'
      path: '/api/chat/case-02-crate'
      fullPath: '/api/chat/case-02-crate'
      preLoaderRoute: typeof ApiChatCase02CrateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat/case-02-bar': {
      id: '/api/chat/case-02-bar'
      path: '/api/chat/case-02-bar'
      fullPath: '/api/chat/case-02-bar'
      preLoaderRoute: typeof ApiChatCase02BarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat/case-01-chocolate': {
      id: '/api/chat/case-01-chocolate'
      path: '/api/chat/case-01-chocolate'
      fullPath: '/api/chat/case-01-chocolate'
      preLoaderRoute: typeof ApiChatCase01ChocolateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat/case-01-canvas': {
      id: '/api/chat/case-01-canvas'
      path: '/api/chat/case-01-canvas'
      fullPath: '/api/chat/case-01-canvas'
      preLoaderRoute: typeof ApiChatCase01CanvasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat/case-01': {
      id: '/api/chat/case-01'
      path: '/api/chat/case-01'
      fullPath: '/api/chat/case-01'
      preLoaderRoute: typeof ApiChatCase01RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PlayRouteChildren {
  PlayCase01Route: typeof PlayCase01Route
  PlayCase02Route: typeof PlayCase02Route
  PlayCase03Route: typeof PlayCase03Route
  PlayIndexRoute: typeof PlayIndexRoute
}

const PlayRouteChildren: PlayRouteChildren = {
  PlayCase01Route: PlayCase01Route,
  PlayCase02Route: PlayCase02Route,
  PlayCase03Route: PlayCase03Route,
  PlayIndexRoute: PlayIndexRoute,
}

const PlayRouteWithChildren = PlayRoute._addFileChildren(PlayRouteChildren)

interface PrintablesRouteChildren {
  PrintablesFractionsL1Route: typeof PrintablesFractionsL1Route
}

const PrintablesRouteChildren: PrintablesRouteChildren = {
  PrintablesFractionsL1Route: PrintablesFractionsL1Route,
}

const PrintablesRouteWithChildren = PrintablesRoute._addFileChildren(
  PrintablesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlayRoute: PlayRouteWithChildren,
  PrintablesRoute: PrintablesRouteWithChildren,
  ApiChatCase01Route: ApiChatCase01Route,
  ApiChatCase01CanvasRoute: ApiChatCase01CanvasRoute,
  ApiChatCase01ChocolateRoute: ApiChatCase01ChocolateRoute,
  ApiChatCase02BarRoute: ApiChatCase02BarRoute,
  ApiChatCase02CrateRoute: ApiChatCase02CrateRoute,
  ApiChatCase02PanelsRoute: ApiChatCase02PanelsRoute,
  ApiChatCase03DisksRoute: ApiChatCase03DisksRoute,
  ApiChatCase03GardenRoute: ApiChatCase03GardenRoute,
  ApiChatCase03TanksRoute: ApiChatCase03TanksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
