/**
 * Router bootstrap.
 *
 * `routeTree` is auto-generated by the TanStack Router Vite plugin from
 * files in `src/routes/` — never edit `routeTree.gen.ts` by hand. Add a
 * new page by creating a new route file; the plugin registers it on save.
 *
 * A fresh QueryClient is created per request so SSR does not leak cache
 * between users. `defaultPreloadStaleTime: 0` keeps loader data honest
 * on client-side navigation.
 */
import { QueryClient } from "@tanstack/react-query";
import { createRouter } from "@tanstack/react-router";
import { routeTree } from "./routeTree.gen";

export const getRouter = () => {
  const queryClient = new QueryClient();

  const router = createRouter({
    routeTree,
    context: { queryClient },
    scrollRestoration: true,
    defaultPreloadStaleTime: 0,
  });

  return router;
};
